version: '3.3'

services:
  db:
    image: mysql:8.0
    container_name: mybank-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mybankdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mybank-db-data:/var/lib/mysql
    networks:
      - mybank-network

  app:
    build: .
    container_name: mybank-app
    environment:
      MYSQL_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
      MYSQL_DATABASE: mybankdb
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - mybank-network

volumes:
  mybank-db-data:

networks:
  mybank-network:
    driver: bridge